### ISSUE TITLE
Problem with command in group chats

### ISSUE THREAD

**Issue by mikexine** [leonjza/hogar#1]
Hi!
Nice work! I am playing around a bit with some plugins. I did this: 
- setup the bot with BotFather (including commands) 
- setup a plugin 
- add my bot to a group chat (this chat has also other bots inside) 
- Send the commands through telegram (when I click on the "/", instead of typing /myCommand) - this means that the command sent is /myCommand@MyBot

The bot doesn't reply to this input - however, it replies correctly if I just send "/myCommand".

I tried to add to the list of commands in the plugin file both commands (['myCommand'], ['myCommand@MyBot']) but it doesn't look to work..

**Comment by leonjza** [comment]
I actually have not tested this with multiple bots in the same group chat yet. Lemme check it out and see what its doing under the hood! :)

**Comment by mikexine** [comment]
Sure! Let me know if I can help you!

**Comment by leonjza** [comment]
You can git pull to get cb93c6d80cfb455d5af025 and test please :)

**Comment by leonjza** [comment]
ping @mikexine :)
