### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by elia7x** [leonjza/hogar#3]
Hi 
I send the : python hogarctl.py start 
have a error  

.__
|  |__   ____   _________ _______
|  |  \ /  _ \ / _____  \_  __ \
|   Y  (  <_> ) /_/  > __ |  | \/
|**_|  /_**_/___  (____  /**|
     \/      /___**/     \/
                   v1.0 - @leonjza
- Loading plugins...
- Loaded plugins for 8 message types: document; text; sticker; contact; video;
  location; photo; audio
- Starting Daemon
  Starting...
  Traceback (most recent call last):
  File "hogarctl.py", line 151, in <module>
    app.start()
  File "C:\Users\Om!D\Desktop\hogar-master\hogar\Utils\Daemon.py", line 177, in
  start
  self.daemonize()
  File "C:\Users\Om!D\Desktop\hogar-master\hogar\Utils\Daemon.py", line 67, in d
  aemonize
  pid = os.fork()
  AttributeError: 'module' object has no attribute 'fork'

how can fix this ? 
tank you <3

**Comment by leonjza** [comment]
Looks like you are running on Windows which does not know what forking is. Unfortunately Hogar is written / tested only on Linux based systems. Maybe at a later stage I will be able to test and try port it to work in Windows too, but as it is now, Windows is not supported.
